version: "3.7"
services:
  hadoop-master:
    image: hadoop:2.9.2
    hostname: hadoop-master
    container_name: hadoop-master
    ports:
      - 50070:50070
    volumes:
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/hadoop_cluster_ssh/hadoop-master:/root/.ssh
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/hadoop-config/common/:/apache/hadoop/etc/hadoop/
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/master-data/:/data/
  hadoop-slave1:
    image: hadoop:2.9.2
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    volumes:
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/hadoop_cluster_ssh/hadoop-slave1:/root/.ssh
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/hadoop-config/common/:/apache/hadoop/etc/hadoop/
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/slave1-data/:/data/
  hadoop-slave2:
    image: hadoop:2.9.2
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    volumes:
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/hadoop_cluster_ssh/hadoop-slave2:/root/.ssh
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/hadoop-config/common/:/apache/hadoop/etc/hadoop/
      - /Users/luo-songtao/workspace/hadoop-ecosystem-docker/hadoop/example/volumes/slave2-data/:/data/

